# Generated by Django 5.1.3 on 2025-04-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.TextField(null=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('title', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('job_type', models.TextField(null=True)),
                ('salary', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('notice_period', models.CharField(choices=[('immediate', 'Immediate Join'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month')], max_length=100, null=True)),
                ('linkedin_url', models.TextField(null=True)),
                ('portfolio_url', models.TextField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('upload_cv', models.FileField(null=True, upload_to='cv')),
                ('cover_letter', models.FileField(null=True, upload_to='cover_letter')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.jobposting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
